### ISSUE TITLE
[Question] Additional input sources?

### ISSUE THREAD

**Issue by tofublock** [firefrei/docker-snapcast#11]
Are you interested in making this container even more versatile by adding input sources like DLNA, radio streams, podcasts?

I was considering adding a Mopidy installation with a few select [extensions](https://mopidy.com/ext/) (e.g., Jellyfin, RadioNet or TuneIn, Podcast), and sane defaults or maybe a config script like you have it already.

Happy to contribute if you think that's a good idea. I just don't want to introduce bloat if you want to keep it lean.
What do you think?

**Comment by firefrei** [comment]
I already spent some thoughts about that. However, my aim was/is to create a basic snapserver container that supports remote streaming (Airplay, Spotify Connect).
For a full-featured media server experience you may consider [music assistant](https://github.com/music-assistant/server), which supports multiple input media sources (Soundcloud, TuneIn, Spotify, Apple Music, ...) to multiple output sources (Snapcast, AirPlay).
Works quite well. I use music assistant as the music provider and then stream to my snapcast clients. I use my own snapcast server container, as Spotify Connect and Airplay are not yet supported by music assistant.

**Comment by tofublock** [comment]
I see, good thing I asked. 😃
