### ISSUE TITLE
Rebuild docker container to support Spotify OAUTH2

### ISSUE THREAD

**Issue by nullmonk** [firefrei/docker-snapcast#15]
Librespot has [added OAUTH2 support](https://github.com/librespot-org/librespot/commit/4f9151c6429e314c5916fdcd7f75ec5478624652). Please rebuild the docker container with the new version.

**Comment by firefrei** [comment]
Done 👌🏻

**Comment by nullmonk** [comment]
Thank you!!

**Comment by dekiesel** [comment]
@firefrei , Thank you! Would you mind updating the documentation? I am not sure how to use oauth with your excellent container. Thank you very much!

**Comment by firefrei** [comment]
@dekiesel I haven't tried out Librespot with OAUTH2 until now.

Did anybody go through the authentication steps with the Librespot libary and can summarize it?

**Comment by dekiesel** [comment]
@firefrei, sorry, I actually forgot about this comment. It works for me with oauth like this:

In your `snapserver.conf`:

```source = spotify:///librespot?name=Spotify&devicename=Snapcast&bitrate=320&cache=/var/cache/librespot&cache-size-limit=1G&wd_timeout=7800&access-token=<YOUR_TOKEN_HERE>```

To get the token click on [this link](https://developer.spotify.com/documentation/web-playback-sdk/tutorials/getting-started) and reveal your token
![image](https://github.com/user-attachments/assets/ccf6c387-145d-4176-a3fb-a61754f4e1bb)

It is possible that you need to create an app first (I already had one so I am not sure): Top right corner->your username->dashboard->create app (make sure to click give it Web SDK permissions.

**Comment by firefrei** [comment]
I have added the access-token as an environment variable: `SPOTIFY_ACCESS_TOKEN`
... and removed username and password
