### ISSUE TITLE
airplay possibly not broadcasting as available device  

### ISSUE THREAD

**Issue by Elix3r** [firefrei/docker-snapcast#6]
Hello, thanks for making this repo btw, my media server died and I took a leap to using docker for snapcast. I was wondering though I was able to get spotify working just fine, however for airplay doesnt seem to want to broadcast as a available device. 
This is what I have under root/snapserver/snapserver.conf , though I dont see any configuration files for shairplay during deployment or anything I can view for logging. 

[stream]
#spotify
source = librespot:///librespot?name=Spotify&devicename=Snapcast&bitrate=320&dryout_ms=2000&volume=100&username=username@domain.com&password=password

#also tried without "source =" in front
source = airplay:///shairport-sync?name=Airplay&devicename=shairplay&password=airmusic

sampleformat = 48000:16:2

**Comment by Elix3r** [comment]
[airplayissue.txt](https://github.com/firefrei/docker-snapcast/files/11587578/airplayissue.txt)

heres the full snapserver.conf file
is there perhaps a mount or config file i need to add for airplay?

**Comment by firefrei** [comment]
Hi,

for configuring snapcast correctly, please refer to the official snapcast documentation: https://github.com/badaix/snapcast/blob/develop/doc/configuration.md

However, I can tell that I am using the image myself without any problems.
As an example, please find below my config.

Snapcast looks for its configuration file (within the container) at the following file path: 
`/root/.config/snapserver/snapserver.conf`
This is how my personal configuration looks like at the moment - without any guarantee :-)
```ini
#...
[stream]
stream = airplay:///shairport-sync?name=AirplayCh1&devicename=SnapcastChannel1&port=5000
stream = spotify:///librespot?name=Spotify&username=<me>&password=<hidden>&devicename=Snapcast&bitrate=320&disable_audio_cache=false&killall=false
#...
```
This enables me to select a AirPlay speaker as well as a speaker within Spotify.

I hope this helps and you can get it working,
Cheers!

**Comment by Elix3r** [comment]
thanks for the quick reply.  it looks like it was on my end, I still have some issues on the networking side but overall household is happy with host-networking enabled in kubernetes/rancher. It works in a containerized enviroment for spotify but for airplay it requires a bridge even though the ports are enabled in metallb. I'll figure that out later lol.

**Comment by firefrei** [comment]
Well, using Airplay/Shairport behind a NAT can cause problems. Avahi respectively mDNS is, as far as I know, limited to a layer-2 network domain, i.e., the announcements are only broadcasted in the network directly connected to the container. As a consequence, you may not be able to use Airplay in Docker or Kubernetes environments, where 'internal' (overlay) networks are used. Maybe a mDNS-Repeater can work around this here. Or when using Docker, use bridge mode or macvlans here.
